# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 440c201bb58f5fbd6f027c0849acb3eb8a5dd1216e326e857ac77b2b808a3e0030ec86dd41d831b297d45fbc73a2b76c4962a55189553d84cdb0d4849a146d26

test:
  secret_key_base: a50d41ee86cd5b2b9a8344fc8385644032c27bc0ff1a5a8e09f797580f7b40ab6230c466e94a9da3925447a96647885857714246fa5397f8fb40f8abbbbc105f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
